#!/usr/bin/env python3
"""Apply publishable package metadata to a library generated by `bal edi libgen`.

`libgen` writes a minimal Ballerina.toml (org, name, version, distribution,
export, edi dependency) and a placeholder Package.md/Module.md. Neither carries
the keywords, icon, licence, authors or repository that Ballerina Central and
the connector store need, and libgen rewrites the file on every run, so the
metadata cannot simply be committed alongside the generated sources. This
script re-applies it from metadata/packages.json after each generation.

It preserves everything libgen computed (`export`, `[[dependency]]`) and only
adds or overwrites the [package] fields it owns.

Usage:
    python3 scripts/apply_package_metadata.py <package-dir> <domain> <version> [org]

`org` defaults to the organization in metadata/packages.json; pass it to publish
the same sources under a different organization.
"""
import json
import pathlib
import re
import shutil
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
METADATA = REPO / "metadata"

README = """# Ballerina EDIFACT D03A {display} library

## Overview

This package provides Ballerina record types and parser functions for the
{count} UN/EDIFACT D03A messages grouped under **{domain}**: {overview}

Each message is exposed as its own submodule, so a program only pulls in the
records for the messages it actually handles. The records and schemas are
generated from the UN/EDIFACT D03A directory with the
[Ballerina EDI tool](https://central.ballerina.io/ballerina/edi) and are
envelope-aware: an interchange is parsed from `UNB` through `UNZ`, including the
`UNH`/`UNT` message header and trailer.

## Quick start

To use this library in your Ballerina application, import the package and the
submodules for the messages you handle.

### Step 1: Import the library

```ballerina
import ballerina/io;
import ballerinax/edifact.d03a.{domain};
import ballerinax/edifact.d03a.{domain}.m{sample};
```

### Step 2: Read an EDI message

Convert an EDIFACT interchange into a Ballerina record:

```ballerina
public function main() returns error? {{
    string ediText = check io:fileReadString("{sample_lower}.edi");
    m{sample}:EDI_{sample}_{sample} message =
        check {domain}:fromEdiString(ediText, {domain}:EDI_{sample}).ensureType();
    io:println(message);
}}
```

### Step 3: Write an EDI message

Convert a Ballerina record back into an EDIFACT interchange:

```ballerina
string ediText = check {domain}:toEdiString(message, {domain}:EDI_{sample});
```

`{domain}:getEDINames()` returns every message name this package supports.
`interchangeFromEdiString` and `interchangeToEdiString` give access to the full
`UNB`/`UNZ` interchange, and `headersFromEdiString` reads just the headers.

## Supported messages

| Message | Description | Module |
| ------- | ----------- | ------ |
{table}
"""


def load(path):
    return json.loads((METADATA / path).read_text(encoding="utf-8"))


def toml_string_array(values):
    return "[" + ", ".join(f'"{value}"' for value in values) + "]"


def render_ballerina_toml(existing, domain, version, org, common, package):
    """Rebuild [package] with the publishable fields, keeping libgen's own."""
    exported = re.search(r"^export\s*=\s*\[(.*)\]\s*$", existing, re.MULTILINE)
    dependencies = existing[existing.index("[[dependency]]"):].rstrip() \
        if "[[dependency]]" in existing else ""

    keywords = package.get("keywords", []) + common["keywords"] + \
        [f"Name/{package['displayName']}"]

    name = f"edifact.d03a.{domain}"
    toml = "\n".join([
        "[package]",
        f'org = "{org}"',
        f'name = "{name}"',
        f'version = "{version}"',
        f'distribution = "{common["distribution"]}"',
        f'authors = {toml_string_array(common["authors"])}',
        f'keywords = {toml_string_array(keywords)}',
        f'repository = "{common["repository"]}"',
        f'icon = "{common["icon"]}"',
        f'license = {toml_string_array(common["license"])}',
    ]) + "\n"

    if dependencies:
        toml += "\n" + dependencies + "\n"

    # libgen writes the deprecated `export` list under [package]; re-emit it as
    # [[package.modules]] so `bal pack` does not warn. The default module is
    # exported implicitly.
    if exported:
        for module in (m.strip().strip('"') for m in exported.group(1).split(",")):
            if module and module != name:
                toml += (f'\n[[package.modules]]\nname = "{module}"\n'
                         "export = true\n")
    return toml


def render_readme(domain, package, titles, modules):
    codes = sorted(modules)
    table = "\n".join(
        f"| `{code}` | {titles[code]} | `edifact.d03a.{domain}.m{code}` |"
        for code in codes)
    sample = "ORDERS" if "ORDERS" in codes else codes[0]
    return README.format(
        display=package["displayName"].replace("EDIFACT D03A ", ""),
        domain=domain,
        count=len(codes),
        overview=package["overview"],
        sample=sample,
        sample_lower=sample.lower(),
        table=table,
    )


def main():
    if len(sys.argv) not in (4, 5):
        print(__doc__)
        return 2
    package_dir, domain, version = pathlib.Path(sys.argv[1]), sys.argv[2], sys.argv[3]

    config = load("packages.json")
    titles = load("message-titles.json")
    common, package = config["common"], config["packages"][domain]
    org = sys.argv[4] if len(sys.argv) == 5 else common["org"]

    modules = [path.name[1:] for path in (package_dir / "modules").iterdir()
               if path.is_dir() and path.name.startswith("m")]
    if not modules:
        raise SystemExit(f"error: no generated modules under {package_dir}")

    toml_path = package_dir / "Ballerina.toml"
    toml_path.write_text(
        render_ballerina_toml(toml_path.read_text(encoding="utf-8"),
                              domain, version, org, common, package),
        encoding="utf-8")

    (package_dir / "README.md").write_text(
        render_readme(domain, package, titles, modules), encoding="utf-8")
    shutil.copyfile(METADATA / common["icon"], package_dir / common["icon"])

    # libgen still emits the pre-2201.9 documentation files; README.md is now
    # the default and Ballerina warns if both are present.
    for stale in ("Package.md", "Module.md"):
        (package_dir / stale).unlink(missing_ok=True)

    # rest_connector.bal declares `service ... on new http:Listener(9090)` in the
    # package's default module. A module-level service in a *library* starts
    # listening as soon as the package is imported, so importing one of these
    # packages silently opens port 9090 and keeps the program alive, and
    # importing any two fails at runtime with "Address already in use". A REST
    # wrapper belongs in a sample application, not in a published library.
    (package_dir / "rest_connector.bal").unlink(missing_ok=True)

    print(f"applied metadata to {package_dir} "
          f"({org}/edifact.d03a.{domain}:{version}, {len(modules)} modules)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
